# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f090c477f494c35f3934e16933a8a3c36cf8d966684559350ba486d5437ba6f665c12a70b7b5787cbe4c2019881adf66a2f2aa848250c5ca257ab8837e957e2f

test:
  secret_key_base: 1b9be10adc6a682c3beeb2a887cf4e4ff60e0be38ac4bc323c96715e1a97406eda7f4ad497193e72bb774fedd9de9481423f7569c08c09ccae507fc3de5db011

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
